os: osx
osx_image: xcode11.3
language: objective-c
before_script: 
  - pod lib lint
matrix:
  include:
    - env: NAME=Xcode DESTINATION="platform=iOS Simulator,name=iPhone Xs"
script:
  - xcodebuild test -project EventBottle.xcodeproj -scheme EventBottle -destination "${DESTINATION}"
